### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by daviddahl** [devgeeks/echidna.js#1]
Naturally, naming things is hard. I would like to see an awesome name for this project. BTW: is this project just covering the client crypto and server storage APIs?

**Comment by devgeeks** [comment]
Yeah, this is a temporary name... just to have somewhere to work together...

**Comment by devgeeks** [comment]
closed!

**Comment by devgeeks** [comment]
NOTE: Name changed to Echidna.js
